apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: node-api
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
              - "localhost:8080"
              - "110.1.0.131:8080"
              - "110.1.0.123:8080"
              - "110.1.0.117:8080"
              - "110.1.0.116:8080"
              - "110.1.0.125:8080"
