apiVersion: v1
kind: Service
metadata:
  name: mon-service-externe
spec:
  selector:
    app: mon-application
  ports:
    - protocol: TCP
      port: 81 # Port sur lequel le service écoutera
      targetPort: 8080 # Port auquel les requêtes seront acheminées dans les pods
  type: LoadBalancer # Type de service pour l'exposition externe
